-- liquibase formatted sql

-- private Long id;
-- private String username;
-- private String email;
-- private String password;
-- private String bio;
-- private String image;
-- private LocalDateTime createdAt;
-- private LocalDateTime updatedAt;
-- private Set<Account> followers;
-- private Set<Account> followings;

-- changeset popov.d:1
CREATE TABLE IF NOT EXISTS account
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL,
    password VARCHAR(64) NOT NULL,
    bio TEXT NOT NULL,
    image VARCHAR(255) NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),

    CONSTRAINT pk_account PRIMARY KEY(id),
    CONSTRAINT uq_email UNIQUE(email)
);
-- rollback DROP TABLE account

-- changeset popov.d:2
CREATE TABLE IF NOT EXISTS account_relation
(
    id_followee bigint,
    id_follower bigint,

    CONSTRAINT pk_account_relation PRIMARY KEY(id_followee, id_follower),
    CONSTRAINT fk_id_followee FOREIGN KEY(id_followee) REFERENCES account(id),
    CONSTRAINT fk_id_follower FOREIGN KEY(id_follower) REFERENCES account(id),
    CONSTRAINT self_follow_reject_check CHECK (id_followee != id_follower)
);
-- rollback DROP TABLE account_relation
